### ISSUE TITLE
Not auto clear previous highlight when click other tag

### ISSUE THREAD

**Issue by JLamp07** [vmkononenko/pair-tag-highlighter#1] opened 2014-08-05 03:31 UTC
Hi you! Thanks you for make this geany plugin. Very usefull.

When i click html tag 1, it highlight is nice. But i click other tag, highlight of tag 1 not clear highlight.

You can see below image of me.

Thanks for read!

![geany-pairhighlight](https://cloud.githubusercontent.com/assets/5916323/3806624/dc307bac-1c50-11e4-8089-5b27db3269b1.png)

**Comment by vmkononenko** [comment] 2015-01-05 15:52
Hello!
I am very sorry for such delay with reply. I haven't seen email notification about this issue because it went to spam. If the issue is still reproducible, could you please share problematic code?
I received several reports same with this one but I was unable to reproduce on my PC.

Thank you!

**Comment by ricardoabarza** [comment] 2015-03-02 16:45
Hi!, I have the same problem :(

You can see the problem code here: http://pastebin.com/z9D3tgm7

If you have news, please notice me. Thanks a lot for this plugin !  :)

![captura de pantalla de 2015-03-02 13 41 55](https://cloud.githubusercontent.com/assets/8622394/6445410/684582b4-c0e2-11e4-89d8-ac2c6751454c.png)

**Comment by vmkononenko** [comment] 2015-03-09 15:14
Hi Guys,
Thank you both for reporting!

I spent some time with debugging and found the issue. You may track it at [Geany-Gevel](http://lists.geany.org/pipermail/devel/2015-March/009276.html) mailing list.
While discussion in mailing list is not yet finished and fix will be proposed only in next Geany release, I propose you to downgrade to Geany 1.23.1 and install plugin as described [here](http://kononenko.ws/en/blog/2013-06-06/pairtaghighlighter_for_geany_1.23). PairTagHighlighter is working correctly on Geany 1.23.1.

I will update you as soon as the issue is finally fixed.

**Comment by vmkononenko** [comment] 2015-03-09 20:44
Guys,

Root cause is found, fix is provided and merged. Was my mistake.
Will be available with the next release of Geany plugins.

Thanks for participation!

**Closed by vmkononenko** 2015-03-09 20:44 UTC
Labels: bug

**Comment by vmkononenko** [comment] 2015-03-09 21:28
In order not to wait next official Geany plugins release, I've prepared 64bit version of plugin for Linux.
You may download it here - http://kononenko.ws/en/blog/2015-03-09/updated_pairtaghighlighter_plugin_for_geany_1.24

**Comment by ricardoabarza** [comment] 2015-03-10 03:04
Really thank you, work perfectly, but I had to copy the file in /usr/local/lib/geany/. Maybe is because I compiled geany from source and I don't installed from repositories.

Thanks also for the recognition :D

see you later. from Chile
